In [ ]:
import numpy as np
player_data=np.array([
    ('Alice', 1200, 10),
    ('Bob', 950, 8),
    ('Charlie', 1500, 12),
    ('David', 800, 5)
], dtype=[('name', 'U10'), ('score', 'i4'), ('level', 'i4')])
highest_level_player=np.argmax(player_data['level'])
player_data['score'][highest_level_player] += 100 
new_player=np.array([('Eve', 1050, 7)], dtype=player_data.dtype)
player_data=np.append(player_data, new_player)
new_player=np.array([('Frank', 1100, 6)], dtype=player_data.dtype)
player_data=np.insert(player_data, 2, new_player)
lowest_score_player=np.argmin(player_data['score'])
player_data=np.delete(player_data, lowest_score_player)
print("\nFinal player data after deletion:\n", player_data)



Final player data after deletion:
 [('Alice', 1200, 10) ('Bob',  950,  8) ('Frank', 1100,  6)
 ('Charlie', 1600, 12) ('Eve', 1050,  7)]


In [ ]:
import numpy as np


daily_visitors=np.array([150, 200, 170, 180, 210, 190, 160])
pages_viewed=np.array([80, 120, 75, 130, 115, 95, 85])
print("Daily Visitors:\n", daily_visitors)
print("Pages Viewed:\n", pages_viewed)
visitors_shallow_copy=daily_visitors.view()
pages_viewed_deep_copy=pages_viewed.copy()
print("\nShallow Copy of Visitors:\n", visitors_shallow_copy)
print("Deep Copy of Pages Viewed:\n", pages_viewed_deep_copy)
combined_array=np.concatenate((daily_visitors, pages_viewed))
print("\nConcatenated Array:\n", combined_array)
above_threshold=combined_array[combined_array > 100]
below_threshold=combined_array[combined_array <= 100]
print("\nEntries with more than 100 pages viewed:\n", above_threshold)
print("Entries with 100 pages or fewer viewed:\n", below_threshold)
daily_visitors[0]=400 
pages_viewed[0]=200  
print("\nModified Daily Visitors:\n", daily_visitors)
print("Shallow Copy of Visitors (should reflect changes):\n", visitors_shallow_copy)
print("\nModified Pages Viewed:\n", pages_viewed)
print("Deep Copy of Pages Viewed (should not reflect changes):\n", pages_viewed_deep_copy)


Daily Visitors:
 [150 200 170 180 210 190 160]
Pages Viewed:
 [ 80 120  75 130 115  95  85]

Shallow Copy of Visitors:
 [150 200 170 180 210 190 160]
Deep Copy of Pages Viewed:
 [ 80 120  75 130 115  95  85]

Concatenated Array:
 [150 200 170 180 210 190 160  80 120  75 130 115  95  85]

Entries with more than 100 pages viewed:
 [150 200 170 180 210 190 160 120 130 115]
Entries with 100 pages or fewer viewed:
 [80 75 95 85]

Modified Daily Visitors:
 [400 200 170 180 210 190 160]
Shallow Copy of Visitors (should reflect changes):
 [400 200 170 180 210 190 160]

Modified Pages Viewed:
 [200 120  75 130 115  95  85]
Deep Copy of Pages Viewed (should not reflect changes):
 [ 80 120  75 130 115  95  85]
