### Task 01

In [3]:
import numpy as np

array_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
array_2d = array_1d.reshape(4, 5)
array_2d[:, -1] = 0
flattened_array = array_2d.flatten()
print(flattened_array)


[ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


### Task 02

In [4]:
import numpy as np

array = np.random.randint(10, 51, size=(5, 5))
print("Generated Array:")
print(array)
print("\nRow Statistics:")
for i in range(array.shape[0]):
    row = array[i]
    print(f"Row {i+1}:")
    print(f"  Mean: {np.mean(row)}")
    print(f"  Sum: {np.sum(row)}")
    print(f"  Minimum: {np.min(row)}")
    print(f"  Maximum: {np.max(row)}")
print("\nColumn Statistics:")
for j in range(array.shape[1]):
    column = array[:, j]
    print(f"Column {j+1}:")
    print(f"  Mean: {np.mean(column)}")
    print(f"  Sum: {np.sum(column)}")
    print(f"  Minimum: {np.min(column)}")
    print(f"  Maximum: {np.max(column)}")


Generated Array:
[[20 14 12 32 50]
 [49 47 13 19 24]
 [31 46 27 17 35]
 [45 30 48 14 13]
 [44 24 29 39 12]]

Row Statistics:
Row 1:
  Mean: 25.6
  Sum: 128
  Minimum: 12
  Maximum: 50
Row 2:
  Mean: 30.4
  Sum: 152
  Minimum: 13
  Maximum: 49
Row 3:
  Mean: 31.2
  Sum: 156
  Minimum: 17
  Maximum: 46
Row 4:
  Mean: 30.0
  Sum: 150
  Minimum: 13
  Maximum: 48
Row 5:
  Mean: 29.6
  Sum: 148
  Minimum: 12
  Maximum: 44

Column Statistics:
Column 1:
  Mean: 37.8
  Sum: 189
  Minimum: 20
  Maximum: 49
Column 2:
  Mean: 32.2
  Sum: 161
  Minimum: 14
  Maximum: 47
Column 3:
  Mean: 25.8
  Sum: 129
  Minimum: 12
  Maximum: 48
Column 4:
  Mean: 24.2
  Sum: 121
  Minimum: 14
  Maximum: 39
Column 5:
  Mean: 26.8
  Sum: 134
  Minimum: 12
  Maximum: 50


### Task 03

In [5]:
import numpy as np

identity_matrix = np.eye(4)
identity_matrix += np.eye(4) * 5
identity_matrix[-1] = 1
print(identity_matrix)



[[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [1. 1. 1. 1.]]


### Task 04

In [6]:
import numpy as np

array = np.random.randint(0, 21, size=15)
print("Generated Array:")
print(array)
unique, counts = np.unique(array, return_counts=True)
occurrences = dict(zip(unique, counts))
print("\nOccurrences of each unique value:")
for value, count in occurrences.items():
    print(f"Value {value}: {count} times")
indices_greater_than_10 = np.where(array > 10)[0]
print("\nIndices of elements greater than 10:")
print(indices_greater_than_10)


Generated Array:
[18  6 17  3 11  2  4  8 19  5 17 10 10  0  3]

Occurrences of each unique value:
Value 0: 1 times
Value 2: 1 times
Value 3: 2 times
Value 4: 1 times
Value 5: 1 times
Value 6: 1 times
Value 8: 1 times
Value 10: 2 times
Value 11: 1 times
Value 17: 2 times
Value 18: 1 times
Value 19: 1 times

Indices of elements greater than 10:
[ 0  2  4  8 10]


### Task 05

In [7]:
import numpy as np

array_3x4 = np.random.rand(3, 4)
array_3x4 = np.round(array_3x4, 2)
print("Original Array:\n", array_3x4)
array_3x4[:, 1] = 0.5
print("\nModified Array:\n", array_3x4)


Original Array:
 [[0.86 0.98 0.77 0.17]
 [0.42 0.07 0.61 0.35]
 [0.99 0.01 0.71 0.56]]

Modified Array:
 [[0.86 0.5  0.77 0.17]
 [0.42 0.5  0.61 0.35]
 [0.99 0.5  0.71 0.56]]
